fastq_dir: "test/fastq_dir"
output_dir: "test/output"
ref: "test/ref/CC1.8_v2_pseudomolecule_cat.fa"

## quality control before processing
fastqc:
    params: ""
    threads: 2

## pre-processing if neccessary
# fastp

## variant calling from fastq
bwa_mem:
    params: "-R '@RG\tID:RC3\tSM:RC3\tPL:Illumina'"
    threads: 2


picard_SortSam:
    params: "-SORT_ORDER coordinate -VALIDATION_STRINGENCY SILENT" # index reference
samtools_view:
    params: "-h -b -f 0x02" # convert sam to bam and filter mapping
    threads: 48

MarkDuplicates:
    params: "--remove-sequencing-duplicates false --read-validation-stringency SILENT"
    threads: 2

HaplotypeCaller:
    params: "--read-filter GoodCigarReadFilter --annotate-with-num-discovered-alleles true --max-alternate-alleles 10"
    threads: 2

GenomicDBImport:
    params: ""
    threads: 2

CombineGVCFs:
    params: ""


## stats before and/or after variant filtration
bcftools:
    before: ["gatk_VariantFiltration", "gatk_SelectVariants"]


## variant filtration
gatk_VariantFiltration:
    params: "--cluster-size 4 --cluster-window-size 10 --filter-name 'LOW-QUAL' --filter-expression 'QUAL<200' --filter-name 'LOW-MQ' --filter-expression 'MQ0>=4 && ((MQ0/(1.0 * DP)) > 0.1 )' "
    suffix: "_VariantFiltration"
gatk_SelectVariants:
    params: ""
    suffix: "_SelectVariants"
vcftools:
    params: "" # singleton, doubleton
    suffix: "_vcftools"
